version: '3.8'

services:
  obsidian-docs:
    build: .
    container_name: obsidian-docs-web
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - OBSIDIAN_VAULT_PATH=/app/docs
      - ANALYSIS_SERVICE_URL=http://analysis-service:8001
    volumes:
      - ./docs:/app/docs:ro
      - ./logs:/app/logs
    depends_on:
      - analysis-service
    restart: unless-stopped
    networks:
      - obsidian-network

  # 预留的分析服务容器（后期可替换为C/Rust实现）
  analysis-service:
    image: nginx:alpine
    container_name: obsidian-analysis-service
    ports:
      - "8001:80"
    volumes:
      - ./analysis-service:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - obsidian-network

  # Redis缓存（可选）
  redis:
    image: redis:alpine
    container_name: obsidian-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - obsidian-network

networks:
  obsidian-network:
    driver: bridge

volumes:
  redis-data: 